### ISSUE TITLE
Rust plugin: change static str to String

### ISSUE THREAD

**Issue by ckanner** [DmitrySoshnikov/syntax#76]
The generated code of rust use `&'static str` type. It may has some problem.
This is the sample
```
extern crate syntax;

use std::string::String;
use syntax::Parser;

struct Gremlin {
    s: String,
}

impl Gremlin {
    fn get_s(&self) -> &str {
        &self.s
    }
}

fn exec(g: Gremlin) {
    let mut parser = Parser::new();
    let result = parser.parse(g.get_s());
    println!("{:?}", result);
}

fn main() {
    let g = Gremlin {s: String::from(r#"g.V().and(outE("knows"), has("software", "lang", eq("Java"))).out("person").valueMap("name", "age")"#)};
    exec(g);
}
```
When I run it, the error is:
```
error[E0597]: `g` does not live long enough
  --> src/main.rs:18:31
   |
18 |     let result = parser.parse(g.get_s());
   |                               ^--------
   |                               |
   |                               borrowed value does not live long enough
   |                               argument requires that `g` is borrowed for `'static`
19 |     println!("{:?}", result);
20 | }
   | - `g` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```
I can not change the type of `Gremlin.s` to `&'static str`. Because the struct may generated by protobuf, and it uses `std::string::String`.

It seems the generated code `pub fn parse(&mut self, string: &'static str) -> TResult ` can do some change.

Is there any solution in this sense?

**Comment by DmitrySoshnikov** [comment]
@ckanner, yeah, probably `String` would make more sense here as a more generic, heap-allocated string. We can provide both `parse` method signatures for this (the basic works with `String`, the other one with `&'static str` can calls the base one). I'll appreciate a PR for this in case you'll reach it earlier than me.

**Comment by ckanner** [comment]
@DmitrySoshnikov 
You means a method liked `pub fn parse(&mut self, string: &'static str) -> TResult` called `pub fn parse(&mut self, string: String) -> TResult`. And all the `&'static str` type in the `lib.rs` should changes to `String` type.

**Comment by DmitrySoshnikov** [comment]
@ckanner, yeah, something like this. We can make `String` the main type used everywhere in the parser, and `&'static str` just creates a `String`, and calls the default method. See these templates, you can change those, and see if it works, then feel free to submit a PR: https://github.com/DmitrySoshnikov/syntax/tree/master/src/plugins/rust/templates.

**Comment by ckanner** [comment]
@DmitrySoshnikov I will do this.
