### ISSUE TITLE
Single quotes are not escaped in lex rules for PHP plugin

### ISSUE THREAD

**Issue by rasteiner** [DmitrySoshnikov/syntax#79]
## Problem
The array keys of lex rules in a generated PHP parser don't have correctly escaped single quotes and slashes. 

## Example
for a lex rule like this:

```
\'(?:[^'\\]++|\\.)*+\'     $yytext = substr($yytext, 1, -1); return 'STRING';
```

The expected outcome would be:
```php
[['/^\'(?:[^\'\\\\]++|\\\\.)*+\'/', '_lex_rule1']];
```

The current output is 
```php
[['/^'(?:[^'\\]++|\\.)*+'/', '_lex_rule1']];
```
Which is invalid PHP and also a different regex (unescaped slashes). 

## Context

https://github.com/DmitrySoshnikov/syntax/blob/master/src/plugins/php/php-parser-generator-trait.js#L105
```js
return `['/${lexRule.getRawMatcher()}/${flags.join('')}', ` +
        `'_lex_rule${this._lexHandlers.length}']`;
```

## Solution
escape the array key:

```js
const key = lexRule.getRawMatcher().replace(/\\/g, '\\\\').replace(/'/g, "\\'");
return `['/${key}/${flags.join('')}', ` +
        `'_lex_rule${this._lexHandlers.length}']`;
```

**Comment by DmitrySoshnikov** [comment]
@rasteiner, thanks for the report, I'll take a look. And will appreciate a PR of course, in case you'll reach it earlier than me.
